---
title: "Interactive"
author: "Stephen Powers"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(ggplot2)
library(plotly)
```


```{r include = FALSE}
records = 
  read_csv("./Powerlifting.csv") %>% 
    janitor::clean_names() %>% 
    select(-region, -tested, -group) %>% 
    filter(lbs > 0) %>% 
    mutate(sub_group = str_remove(sub_group, "OPEN")) %>% 
    mutate(sub_group = str_remove(sub_group, "MASTER")) %>% 
    mutate(sub_group = str_remove(sub_group, "JUNIOR")) %>% 
    separate(weight_class, into = c("weightclass_kg" , "weightclass_lbs"), sep = "/") %>% 
    mutate(sub_group = str_to_lower(sub_group)) %>% 
    separate(sub_group, into = c("Gender" , "Age"), sep = "[:digit:]", extra = "merge") %>% 
    mutate(Gender = trimws(Gender, "r")) %>% 
    mutate(as.character(Gender), 
    gender = ifelse(grepl("women", Gender), "Female",
       ifelse(grepl("men", Gender), "Male"))) %>% view
```

```{r plot2, echo=FALSE, warning=FALSE}
plot2 = 
  records %>% 
    mutate(
      weightclass_kg = as.numeric(gsub("[kg - +kg]", "", weightclass_kg)), 
      weightclass_lbs = as.numeric(gsub("lb", "", weightclass_lbs))) %>% 
    ggplot(aes(x = weightclass_kg, y = kgs)) + 
    geom_point(aes(color = Gender, text = member_name)) +
    viridis::scale_color_viridis(
          name = "gender",
          discrete = TRUE
        ) +
    ggtitle("Raw Bench Press Records According to USPA") +
    xlab("Weight in Kilograms") +
    ylab("Max Raw Bench Press in Kilograms") +
    theme_minimal() 

ggplotly(plot2)
```